[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "WC developer handbook for JA"
authors = [{name = "Shohei Tanaka", email = "shohei.t@artws.info"}]
dynamic = ["version", "description"]
